project:
  type: book
  output-dir: _site

execute:
  freeze: auto

book:
  title: "OSSS Ephys Course 2026"
  author:
  - name: Joseph Ziminski
    url: https://github.com/JoeZiminski
    email: j.ziminski@ucl.ac.uk
    orcid: 0000-0003-4286-6868
    corresponding: true
    affiliations:
      - id: SWC
        name: Sainsbury Wellcome Centre, UCL
        department: Sainsbury Wellcome Centre
        group: Neuroinformatics Unit
        city: London
        country: United Kingdom
        url: https://www.sainsburywellcome.org/web/
  - name: Please add your name here
  date: "15/04/2026"
  chapters:
    - index.qmd
    - introduction-presentation.qmd
    - pipeline-walkthrough.qmd
    - preprocessing-steps-presentation.qmd
    - preproecssing-steps-coding.qmd
    - concept-notes.qmd
    - references.qmd
    - planning.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand



